##docker


app: #속성을 바꿀 수 있는 부분 들은 상수 처럼 쓰기 편하도록 만들어놓음
  jwt:
    secret: akjw4egoiaj409gj2a094jg02984jgasegsegase9024jg09ftglk #JWT를 만들 때 쓰는 키, 길이가 짧으면 에러터짐
    header-scheme-name: authorization
    token-type: Bearer
    access token-expiry: 7200000 #단위 : 밀리세컨드 7200000은 7200초(2시간) 엑세스 토큰
    refresh-token-expiry: 1296000000 # 15일 리프레시 토큰

mybatis:
  mapper-locations: mappers/**/*.xml
springdoc:
  swagger-ui:
    path: /swagger.html

#fcm:
#  certification: serviceAccountKey.json

server:
  tomcat:
    threads:
      max: 200


#

#---
#
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/projrental
    username: even_last_5
    password: fines
#
file:
  base-package: /home/download/


